using Microsoft.CodeAnalysis;
using NexYamlSourceGenerator.NexAPI;
using NexYamlSourceGenerator.Templates;
using NexYamlSourceGenerator.Templates.Registration;
using System.Text;

namespace NexYamlSourceGenerator.NexIncremental
{
    internal class SourceCreator
    {
        private static readonly ITemplate thisRegister = new ThisRegister();
        private static readonly ITemplate abstractRegister = new AbstractRegister();
        private static readonly ITemplate interfaceRegister = new InterfaceRegister();
        private static readonly ITemplate serializerEmitter = new SerializeEmitter();
        private static readonly ITemplate deserializeEmitter = new DeserializeEmitter();
        private static readonly ITemplate utf8MemberEmitter = new UTF8MemberEmitter();
        internal string Create(SourceProductionContext ctx, ClassPackage package)
        {
            var info = package.ClassInfo;
            string ns = info.NameSpace != null ? "namespace " + info.NameSpace + ";" : "";
            StringBuilder tempVariables = new StringBuilder();
            foreach (var member in package.MemberSymbols)
            {
                tempVariables.AppendLine($"var temp_{member.Name} = default({member.Type});");
            }
            string Template = @$"// <auto-generated/>
//  This code was generated by Strides YamlSerializer.
//  Do not edit this file.

#nullable enable
using System;
using System.Linq;
using System.Collections.Generic;
using VYaml;
using VYaml.Emitter;
using VYaml.Parser;
using VYaml.Serialization;
{ns}
[System.CodeDom.Compiler.GeneratedCode(""NexYaml"",""1.0.0.0"")]
internal class {info.GeneratorName + info.TypeParameterArguments} : IYamlFormatter<{info.NameDefinition}>
{{
    {utf8MemberEmitter.Create(package)}
    static readonly string AssemblyName = typeof({info.ShortDefinition}).Assembly.GetName().Name;
    string IdentifierTag {{ get; }} = typeof({info.ShortDefinition}).Name;
    Type IdentifierType {{ get; }} = typeof({info.ShortDefinition});

    {info.Accessor} static void Register()
    {{
        {thisRegister.Create(package)}
        {abstractRegister.Create(package)}
        {interfaceRegister.Create(package)}
    }}

    {info.Accessor} void Serialize(ref Utf8YamlEmitter emitter, {info.NameDefinition} value, YamlSerializationContext context)
    {{
        if (value is null)
        {{
            emitter.WriteNull();
            return;
        }}
        if(context.IsMappingEnabled)
            emitter.BeginMapping();
        if(context.IsRedirected || context.IsFirst)
        {{
            emitter.Tag($""!{info.NameSpace}.{info.TypeName},{{AssemblyName}}"");
            context.IsRedirected = false;
            context.IsFirst = false;
        }}
{serializerEmitter.Create(package)}
        if(context.IsMappingEnabled)
            emitter.EndMapping();
    }}

    {info.Accessor} {info.NameDefinition}? Deserialize(ref YamlParser parser, YamlDeserializationContext context)
    {{
        {deserializeEmitter.Create(package)}
    }}
}}
";
            return Template;
        }



    }
}